import { misc, dbsDiary, countMy, nativeWeather, pinglist, ponder, logos } from "../../assets/assets";

export const projects = [
    {
        title: "Ponder Me and You",
        paramsTitle: "ponder",
        description: "Ecommerce site designed and built for a local digital artist",
        pictures: ponder.pictures,
        code: "https://github.com/noblepaper/ponder-me-and-you",
        frameworks: [logos.sketch, logos.react, logos.glamorous, logos.redux, logos.reactRouter, logos.mongodb, logos.express],
        header: ponder.header,
        web: true,
        height: 1830,
    },
    {
        title: "Count My URL",
        paramsTitle: "count-my-url",
        description: "Easily access social share counts for any website.",
        pictures: countMy.pictures,
        code: "https://github.com/noblepaper/count-my-url",
        visit: "https://count-my-url.surge.sh/",
        frameworks: [logos.react, logos.glamorous, logos.d3, logos.webpack],
        header: countMy.header,
        web: true,
        height: 1255,
    },
    {
        title: "DBs Diary",
        paramsTitle: "dbs-diary",
        description: "A simple, purposefully dated, user interface for uninhibited journaling... and other things.",
        pictures: dbsDiary.pictures,
        code: "https://github.com/noblepaper/dbs-diary",
        visit: "https://dbs-diary.herokuapp.com/",
        frameworks: [logos.sketch, logos.react, logos.redux, logos.reactRouter, logos.mongodb, logos.express],
        header: dbsDiary.header,
        web: true,
        height: 1830,
    },
    {
        title: "Native Weather",
        paramsTitle: "native-weather",
        description: "React Native IOS weather app with wildly unneccessary user authentication",
        pictures: nativeWeather.pictures,
        code: "https://github.com/noblepaper/native-weather",
        frameworks: [logos.react, logos.redux, logos.mongodb, logos.express],
        header: nativeWeather.header,
        mobile: true,
        height: 2405,
    },
    {
        title: "Pinglist",
        paramsTitle: "pinglist",
        description: "App design for API monitoring service",
        pictures: pinglist.pictures,
        frameworks: [logos.sketch],
        header: pinglist.header,
        mobile: true,
        height: 2980,
    },
]
